# Do not edit!
# autogenerated by terraform in ooni/devops
[all]
%{ for group_name, server_list in server_groups ~}
%{ for hostname in server_list }
${hostname}
%{ endfor ~}
%{ endfor ~}

%{ for group_name, server_list in server_groups }
[${group_name}]
%{ for hostname in server_list }
${hostname}
%{ endfor ~}
%{ endfor ~}