# Do not edit!
# autogenerated by terraform in ooni/devops
[all]
%{ for hostname in clickhouse_servers ~}
${hostname}
%{ endfor ~}

[clickhouse_servers]
%{ for hostname in clickhouse_servers ~}
${hostname}
%{ endfor ~}

