#!/bin/bash
DOCS_ROOT=dist/docs/
REPO_NAME="ooni/devops"
MAIN_BRANCH="main"
COMMIT_HASH=$(git rev-parse --short HEAD)

mkdir -p $DOCS_ROOT

strip_title() {
    # Since the title is already present in the frontmatter, we need to remove
    # it to avoid duplicate titles
    local infile="$1"
    cat $infile | awk 'BEGIN{p=1} /^#/{if(p){p=0; next}} {print}'
}

generate_doc() {
    local output_file="$1"
    local title="$2"
    local description="$3"
    local slug="$4"
    local input_file="$5"

    cat <<EOF>"$DOCS_ROOT/$output_file"
---
# Do not edit! This file is automatically generated
# version: $REPO_NAME/$input_file:$COMMIT_HASH
title: $title
description: $description
slug: $slug
---
EOF
    echo "[edit file](https://github.com/$REPO_NAME/edit/$MAIN_BRANCH/$input_file)" >> "$DOCS_ROOT/$output_file"
    strip_title "$input_file" >> "$DOCS_ROOT/$output_file"
}


generate_doc "00-index.md" "OONI Devops" "OONI OONI Devops" "devops" "README.md"
generate_doc "01-infrastructure.md" "Infrastructure" "Infrastructure documentation" "devops/infrastructure" "docs/Infrastructure.md"
generate_doc "02-monitoring-alerts.md" "Monitoring" "Monitoring and Alerts documentation" "devops/monitoring" "docs/MonitoringAlerts.md"
generate_doc "03-runbooks.md" "Runbooks" "Runbooks docs" "devops/runbooks" "docs/Runbooks.md"
generate_doc "04-incident-response.md" "Incident response" "Incident response handling guidelines" "devops/incident-response" "docs/IncidentResponse.md"
generate_doc "05-terraform.md" "Terraform setup" "Terraform setup" "devops/terraform" "tf/README.md"
generate_doc "06-ansible.md" "Ansible setup" "Ansible setup" "devops/ansible" "ansible/README.md"
generate_doc "07-tools.md" "Misc Tools" "Misc Tools" "devops/tools" "docs/Tools.md"
generate_doc "08-debian-packages.md" "Debian Packages" "Debian Packages" "devops/debian-packages" "docs/DebianPackages.md"
generate_doc "09-legacy-docs.md" "Legacy Documentation" "Legacy Documentation" "devops/legacy-docs" "docs/LegacyDocs.md"
